package com.hbr.countrycodelib

val countriesArray : MutableList<CountryModel> = mutableListOf(

    CountryModel("United States", "+1", "us"),
    CountryModel("Uruguay", "+598", "uy"),
    CountryModel("Uzbekistan", "+998", "uz"),
    CountryModel("Saint Vincent", "+1 784", "vc"),
    CountryModel("Venezuela", "+58", "ve"),
    CountryModel("British Virgin Islands", "+1 284", "vg"),
    CountryModel("Vietnam", "+84", "vn"),
    CountryModel("Samoa", "+685", "ws"),
    CountryModel("Yemen", "+967", "ye"),
    CountryModel("South Africa", "+27", "za"),
    CountryModel("Zimbabwe", "+263", "zw"),
    CountryModel("Andorra", "+376", "ad"),
    CountryModel("United Arab Emirates", "+971", "ae"),
    CountryModel("Afghanistan", "+93", "af"),
    CountryModel("Colombia", "+57", "co"),
    CountryModel("Antigua and Barbuda", "+1 268", "ag"),
    CountryModel("Anguilla", "+1 264", "ai"),
    CountryModel("Albania", "+355", "al"),
    CountryModel("Armenia", "+374", "am"),
    CountryModel("Angola", "+244", "ao"),
    CountryModel("Argentina", "+54", "ar"),
    CountryModel("Austria", "+43", "at"),
    CountryModel("Australia", "+61", "au"),
    CountryModel("Åland Islands", "+358", "ax"),
    CountryModel("Azerbaijan", "+994", "az"),
    CountryModel("Bosnia and Herzegovina", "+387", "ba"),
    CountryModel("Barbados", "+1 246", "bb"),
    CountryModel("Bangladesh", "+880", "bd"),
    CountryModel("Belgium", "+32", "be"),
    CountryModel("Burkina Faso", "+226", "bf"),
    CountryModel("Bulgaria", "+359", "bg"),
    CountryModel("Bahrain", "+973", "bh"),
    CountryModel("Burundi", "+257", "bi"),
    CountryModel("Benin", "+229", "bj"),
    CountryModel("Bermuda", "+1 441", "bm"),
    CountryModel("Brunei", "+673", "bn"),
    CountryModel("Bolivia", "+591", "bo"),
    CountryModel("Brazil", "+55", "br"),
    CountryModel("Bahamas", "+1 242", "bs"),
    CountryModel("Bhutan", "+975", "bt"),
    CountryModel("Botswana", "+267", "bw"),
    CountryModel("Belarus", "+375", "by"),
    CountryModel("Belize", "+501", "bz"),
    CountryModel("Canada", "+1", "ca"),
    CountryModel("Central African Republic", "+236", "caf"),
    CountryModel("Democratic Republic of the Congo", "+243", "cd"),
    CountryModel("Central African Republic", "+236", "cf"),
    CountryModel("Republic of the Congo", "+242", "cg"),
    CountryModel("China", "+86", "cn"),
    CountryModel("Switzerland", "+41", "ch"),
    CountryModel("Ivory Coast", "+225", "ci"),
    CountryModel("Chile", "+56", "cl"),
    CountryModel("Cameroon", "+237", "cm"),
    CountryModel("Costa Rica", "+506", "cr"),
    CountryModel("Cuba", "+53", "cu"),
    CountryModel("Cape Verde", "+238", "cv"),
    CountryModel("Cyprus", "+357", "cy"),
    CountryModel("Czech Republic", "+420", "cz"),
    CountryModel("Germany", "+49", "de"),
    CountryModel("Djibouti", "+253", "dj"),
    CountryModel("Denmark", "+45", "dk"),
    CountryModel("Dominica", "+1 767", "dm"),
    CountryModel("Algeria", "+213", "dz"),
    CountryModel("Ecuador", "+593", "ec"),
    CountryModel("Estonia", "+372", "ee"),
    CountryModel("Egypt", "+20", "eg"),
    CountryModel("Eritrea", "+291", "er"),
    CountryModel("Spain", "+34", "es"),
    CountryModel("Ethiopia", "+251", "et"),
    CountryModel("India", "+91", "in"),
    CountryModel("Finland", "+358", "fi"),
    CountryModel("Fiji", "+679", "fj"),
    CountryModel("Micronesia", "+691", "fm"),
    CountryModel("France", "+33", "fr"),
    CountryModel("Gabon", "+241", "ga"),
    CountryModel("United Kingdom", "+44", "gb"),
    CountryModel("Grenada", "+1 473", "gd"),
    CountryModel("Georgia", "+995", "ge"),
    CountryModel("Ghana", "+233", "gh"),
    CountryModel("Gambia", "+220", "gm"),
    CountryModel("Guinea", "+224", "gn"),
    CountryModel("Equatorial Guinea", "+240", "gq"),
    CountryModel("Greece", "+30", "gr"),
    CountryModel("Guatemala", "+502", "gt"),
    CountryModel("Guinea-Bissau", "+245", "gw"),
    CountryModel("Guyana", "+592", "gy"),
    CountryModel("Hong Kong", "+852", "hk"),
    CountryModel("Honduras", "+504", "hn"),
    CountryModel("Croatia", "+385", "hr"),
    CountryModel("Haiti", "+509", "ht"),
    CountryModel("Hungary", "+36", "hu"),
    CountryModel("Indonesia", "+62", "id"),
    CountryModel("Ireland", "+353", "ie"),
    CountryModel("Israel", "+972", "il"),
    CountryModel("Iraq", "+964", "iq"),
    CountryModel("Iran", "+98", "ir"),
    CountryModel("Iceland", "+354", "is"),
    CountryModel("Italy", "+39", "it"),
    CountryModel("Jamaica", "+1 876", "jm"),
    CountryModel("Jordan", "+962", "jo"),
    CountryModel("Japan", "+81", "jp"),
    CountryModel("Kenya", "+254", "ke"),
    CountryModel("Kyrgyzstan", "+996", "kg"),
    CountryModel("Cambodia", "+855", "kh"),
    CountryModel("Comoros", "+269", "km"),
    CountryModel("Saint Kitts and Nevis", "+1 869", "kn"),
    CountryModel("North Korea", "+850", "kp"),
    CountryModel("South Korea", "+82", "kr"),
    CountryModel("Cayman Islands", "+1 345", "ky"),
    CountryModel("Kuwait", "+965", "kw"),
    CountryModel("Kazakhstan", "+7", "kz"),
    CountryModel("Laos", "+856", "la"),
    CountryModel("Lebanon", "+961", "lb"),
    CountryModel("Saint Lucia", "+1 758", "lc"),
    CountryModel("Liechtenstein", "+423", "li"),
    CountryModel("Sri Lanka", "+94", "lk"),
    CountryModel("Liberia", "+231", "lr"),
    CountryModel("Lesotho", "+266", "ls"),
    CountryModel("Lithuania", "+370", "lt"),
    CountryModel("Luxembourg", "+352", "lu"),
    CountryModel("Latvia", "+371", "lv"),
    CountryModel("Libya", "+218", "ly"),
    CountryModel("Morocco", "+212", "ma"),
    CountryModel("Monaco", "+377", "mc"),
    CountryModel("Moldova", "+373", "md"),
    CountryModel("Montenegro", "+382", "me"),
    CountryModel("Madagascar", "+261", "mg"),
    CountryModel("Macedonia", "+389", "mk"),
    CountryModel("Mali", "+223", "ml"),
    CountryModel("Myanmar", "+95", "mm"),
    CountryModel("Mongolia", "+976", "mn"),
    CountryModel("Macau", "+853", "mo"),
    CountryModel("Mauritania", "+222", "mr"),
    CountryModel("Montserrat", "+1 664", "ms"),
    CountryModel("Malta", "+336", "mt"),
    CountryModel("Mauritius", "+230", "mu"),
    CountryModel("Maldives", "+960", "mv"),
    CountryModel("Malawi", "+265", "mw"),
    CountryModel("Mexico", "+52", "mx"),
    CountryModel("Malaysia", "+60", "my"),
    CountryModel("Mozambique", "+258", "mz"),
    CountryModel("Namibia", "+264", "na"),
    CountryModel("Niger", "+227", "ne"),
    CountryModel("Nigeria", "+234", "ng"),
    CountryModel("Nicaragua", "+505", "ni"),
    CountryModel("Netherlands", "+31", "nl"),
    CountryModel("Norway", "+47", "no"),
    CountryModel("Nepal", "+977", "np"),
    CountryModel("New Zealand", "+64", "nz"),
    CountryModel("Oman", "+968", "om"),
    CountryModel("Panama", "+507", "pa"),
    CountryModel("Peru", "+51", "pe"),
    CountryModel("Papua New Guinea", "+675", "pg"),
    CountryModel("Philippines", "+63", "ph"),
    CountryModel("Pakistan", "+92", "pk"),
    CountryModel("Poland", "+48", "pl"),
    CountryModel("Puerto Rico", "+1 939", "pr"),
    CountryModel("Portugal", "+351", "pt"),
    CountryModel("Palau", "+680", "pw"),
    CountryModel("Paraguay", "+595", "py"),
    CountryModel("Qatar", "+974", "qa"),
    CountryModel("Romania", "+40", "ro"),
    CountryModel("Serbia", "+381", "rs"),
    CountryModel("Russia", "+7", "ru"),
    CountryModel("Rwanda", "+250", "rw"),
    CountryModel("Saudi Arabia", "+966", "sa"),
    CountryModel("Solomon Islands", "+677", "sb"),
    CountryModel("Seychelles", "+248", "sc"),
    CountryModel("Sudan", "+249", "sd"),
    CountryModel("Sweden", "+46", "se"),
    CountryModel("Singapore", "+65", "sg"),
    CountryModel("Slovenia", "+386", "si"),
    CountryModel("Slovakia", "+421", "sk"),
    CountryModel("Sierra Leone", "+232", "sl"),
    CountryModel("San Marino", "+378", "sm"),
    CountryModel("Senegal", "+221", "sn"),
    CountryModel("Somalia", "+252", "so"),
    CountryModel("Suriname", "+597", "sr"),
    CountryModel("Sao Tome and Principe", "+239", "st"),
    CountryModel("El Salvador", "+503", "sv"),
    CountryModel("Syria", "+963", "sy"),
    CountryModel("Swaziland", "+268", "sz"),
    CountryModel("Turks and Caicos Islands", "+1 649", "tc"),
    CountryModel("Chad", "+235", "td"),
    CountryModel("Togo", "+228", "tg"),
    CountryModel("Thailand", "+66", "th"),
    CountryModel("Tajikistan", "+992", "tj"),
    CountryModel("East Timor", "+670", "tl"),
    CountryModel("Turkmenistan", "+993", "tm"),
    CountryModel("Tunisia", "+216", "tn"),
    CountryModel("Tonga", "+676", "to"),
    CountryModel("Turkey", "+90", "tr"),
    CountryModel("Trinidad and Tobago", "+1 868", "tt"),
    CountryModel("Taiwan", "+886", "tw"),
    CountryModel("Tanzania", "+255", "tz"),
    CountryModel("Ukraine", "+380", "ua"),
    CountryModel("Uganda", "+256", "ug")
)